# Generated by Django 2.1 on 2018-08-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ydl_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instpost',
            name='media',
            field=models.CharField(max_length=60),
        ),
    ]
